Test Case

diff --git a/.github/workflows/project_work1.yml b/.github/workflows/project_work1.yml
--- a/.github/workflows/project_work1.yml
+++ b/.github/workflows/project_work1.yml
@@ -20,13 +20,6 @@ jobs:
           chmod 600 ~/.kaggle/kaggle.json
     env:
       KAGGLE_CONFIG_FILE: ${{ secrets.KAGGLE_CONFIG_FILE }}
-
-  run-pipeline:
-    runs-on: ubuntu-latest
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
-
     - name: Run shell script
       run: |
        bash project/pipeline.sh
@@ -37,3 +30,20 @@ jobs:
           echo "Script failed with exit code $exit_code."
           exit $exit_code
         fi
+
+  # run-pipeline:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - name: Checkout code
+  #     uses: actions/checkout@v2
+
+  #   - name: Run shell script
+  #     run: |
+  #      bash project/pipeline.sh
+  #       exit_code=$?
+  #       if [ $exit_code -eq 0 ]; then
+  #         echo "Script executed successfully."
+  #       else
+  #         echo "Script failed with exit code $exit_code."
+  #         exit $exit_code
+  #       fi
